# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.reservation_build import ReservationBuild  # noqa: E501
from openapi_client.rest import ApiException

class TestReservationBuild(unittest.TestCase):
    """ReservationBuild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReservationBuild
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReservationBuild`
        """
        model = openapi_client.models.reservation_build.ReservationBuild()  # noqa: E501
        if include_optional :
            return ReservationBuild(
                type = 'ReservationBuildFromCatalogOfferings', 
                traveler = [
                    openapi_client.models.traveler_id.TravelerID(
                        @type = 'TravelerDetail', 
                        id = '', 
                        traveler_ref = '', 
                        identifier = openapi_client.models.identifier.Identifier(
                            value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                            authority = 'TVPT', ), )
                    ], 
                form_of_payment = [
                    openapi_client.models.form_of_payment_id.FormOfPaymentID(
                        @type = 'FormOfPaymentPaymentCard', 
                        id = '', 
                        form_of_payment_ref = '', 
                        identifier = openapi_client.models.identifier.Identifier(
                            value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                            authority = 'TVPT', ), )
                    ], 
                payment = [
                    openapi_client.models.payment_id.PaymentID(
                        @type = 'Payment', 
                        id = '', 
                        payment_ref = '', 
                        identifier = openapi_client.models.identifier.Identifier(
                            value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                            authority = 'TVPT', ), )
                    ], 
                reservation_comment = [
                    openapi_client.models.reservation_comment_id.ReservationCommentID(
                        @type = 'ReservationComment', 
                        id = '', )
                    ], 
                primary_contact = [
                    openapi_client.models.primary_contact_id.PrimaryContactID(
                        @type = 'PrimaryContact', 
                        id = '', )
                    ], 
                special_service = [
                    openapi_client.models.special_service_id.SpecialServiceID(
                        @type = 'SpecialService', 
                        id = '', 
                        identifier = openapi_client.models.identifier.Identifier(
                            value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                            authority = 'TVPT', ), )
                    ], 
                accounting = openapi_client.models.accounting_id.AccountingID(
                    @type = 'Accounting', 
                    id = '', 
                    accounting_ref = '', 
                    identifier = openapi_client.models.identifier.Identifier(
                        value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                        authority = 'TVPT', ), ), 
                document_overrides = [
                    openapi_client.models.document_overrides_id.DocumentOverridesID(
                        @type = 'DocumentOverrides', 
                        id = '', 
                        document_overrides_ref = '', 
                        identifier = openapi_client.models.identifier.Identifier(
                            value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                            authority = 'TVPT', ), )
                    ], 
                preference = [
                    openapi_client.models.preference_id.PreferenceID(
                        @type = 'Preference', 
                        id = '', )
                    ], 
                receipt_confirmation = None, 
                travel_agency = None
            )
        else :
            return ReservationBuild(
                type = 'ReservationBuildFromCatalogOfferings',
                traveler = [
                    openapi_client.models.traveler_id.TravelerID(
                        @type = 'TravelerDetail', 
                        id = '', 
                        traveler_ref = '', 
                        identifier = openapi_client.models.identifier.Identifier(
                            value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                            authority = 'TVPT', ), )
                    ],
        )
        """

    def testReservationBuild(self):
        """Test ReservationBuild"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
