# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.availability_source_code_enum import AvailabilitySourceCodeENUM  # noqa: E501
from openapi_client.rest import ApiException

class TestAvailabilitySourceCodeENUM(unittest.TestCase):
    """AvailabilitySourceCodeENUM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailabilitySourceCodeENUM(self):
        """Test AvailabilitySourceCodeENUM"""
        # inst = AvailabilitySourceCodeENUM()

if __name__ == '__main__':
    unittest.main()
