# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.search_vehicle_attributes import SearchVehicleAttributes  # noqa: E501
from openapi_client.rest import ApiException

class TestSearchVehicleAttributes(unittest.TestCase):
    """SearchVehicleAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SearchVehicleAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchVehicleAttributes`
        """
        model = openapi_client.models.search_vehicle_attributes.SearchVehicleAttributes()  # noqa: E501
        if include_optional :
            return SearchVehicleAttributes(
                transmission_type_code = openapi_client.models.code.Code(
                    value = 'INS', 
                    code_context = 'infant with a seat', ), 
                vehicle_category_code = openapi_client.models.code.Code(
                    value = 'INS', 
                    code_context = 'infant with a seat', ), 
                fuel_type_code = openapi_client.models.code.Code(
                    value = 'INS', 
                    code_context = 'infant with a seat', ), 
                vehicle_size_code = openapi_client.models.code.Code(
                    value = 'INS', 
                    code_context = 'infant with a seat', ), 
                door_count = '', 
                air_conditioning_ind = True
            )
        else :
            return SearchVehicleAttributes(
        )
        """

    def testSearchVehicleAttributes(self):
        """Test SearchVehicleAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
