# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.rate_candidates import RateCandidates  # noqa: E501
from openapi_client.rest import ApiException

class TestRateCandidates(unittest.TestCase):
    """RateCandidates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RateCandidates
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RateCandidates`
        """
        model = openapi_client.models.rate_candidates.RateCandidates()  # noqa: E501
        if include_optional :
            return RateCandidates(
                type = 'RateCandidates', 
                rate_candidate = [
                    openapi_client.models.rate_candidate.RateCandidate(
                        @type = 'RateCandidate', 
                        priority = 0, 
                        rate_code = 'HL123', 
                        rate_category = 'All', 
                        chain_code = 'HL', 
                        property_code = 'HL12345', )
                    ], 
                pre_pay_rates_only_ind = True, 
                post_pay_rates_only_ind = True
            )
        else :
            return RateCandidates(
                type = 'RateCandidates',
                rate_candidate = [
                    openapi_client.models.rate_candidate.RateCandidate(
                        @type = 'RateCandidate', 
                        priority = 0, 
                        rate_code = 'HL123', 
                        rate_category = 'All', 
                        chain_code = 'HL', 
                        property_code = 'HL12345', )
                    ],
        )
        """

    def testRateCandidates(self):
        """Test RateCandidates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
