# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.traveler_updated_item_person_name import TravelerUpdatedItemPersonName  # noqa: E501
from openapi_client.rest import ApiException

class TestTravelerUpdatedItemPersonName(unittest.TestCase):
    """TravelerUpdatedItemPersonName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TravelerUpdatedItemPersonName
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TravelerUpdatedItemPersonName`
        """
        model = openapi_client.models.traveler_updated_item_person_name.TravelerUpdatedItemPersonName()  # noqa: E501
        if include_optional :
            return TravelerUpdatedItemPersonName(
                person_name_updatable = openapi_client.models.person_name_updatable.PersonNameUpdatable(
                    @type = 'PersonNameUpdatable', 
                    prefix = 'Snr', 
                    given = 'John', 
                    middle = 'Leslie', 
                    surname = 'Smith', 
                    suffix = 'Mr', )
            )
        else :
            return TravelerUpdatedItemPersonName(
                person_name_updatable = openapi_client.models.person_name_updatable.PersonNameUpdatable(
                    @type = 'PersonNameUpdatable', 
                    prefix = 'Snr', 
                    given = 'John', 
                    middle = 'Leslie', 
                    surname = 'Smith', 
                    suffix = 'Mr', ),
        )
        """

    def testTravelerUpdatedItemPersonName(self):
        """Test TravelerUpdatedItemPersonName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
