# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.traveler import Traveler  # noqa: E501
from openapi_client.rest import ApiException

class TestTraveler(unittest.TestCase):
    """Traveler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Traveler
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Traveler`
        """
        model = openapi_client.models.traveler.Traveler()  # noqa: E501
        if include_optional :
            return Traveler(
                birth_date = 'Sat Jun 05 10:00:00 AEST 2021', 
                gender = 'Male', 
                person_name = openapi_client.models.person_name.PersonName(
                    @type = 'PersonNameDetail', 
                    prefix = 'Mr', 
                    given = 'John', 
                    middle = 'Erick', 
                    surname = 'Smith', ), 
                address = [
                    openapi_client.models.address.Address(
                        @type = 'AddressDetail', 
                        id = 'Address_1', 
                        bldg_room = openapi_client.models.address_bldg_room.AddressBldgRoom(
                            value = 'Moore House, Room 101, 23 ABC Street, Windsor, Berkshire, United Kingdom, SL6 51A', 
                            bulding_ind = True, ), 
                        number = openapi_client.models.address_street_number.AddressStreetNumber(
                            value = '23B ABC Street, Windsor, Berkshire, United Kingdom, SL6 51A', 
                            street_nmbr_suffix = 'B', 
                            street_direction = 'NW', 
                            rural_route_nmbr = '76', 
                            po_box = '1001', ), 
                        street = 'ABC Street', 
                        address_line = S Havana,Opposite to USPS, 
                        city = 'Windsor', 
                        county = 'Berkshire', 
                        state_prov = openapi_client.models.state_prov.StateProv(
                            value = 'CA', 
                            name = 'California', ), 
                        country = openapi_client.models.country.Country(
                            value = 'USA', 
                            id = '23', 
                            name = 'United States', 
                            code_context = 'IATA', ), 
                        postal_code = 'Sl6 1AB', 
                        addressee = '', 
                        role = 'Delivery', )
                    ], 
                telephone = [
                    openapi_client.models.telephone.Telephone(
                        @type = 'Telephone', 
                        country_access_code = '1', 
                        area_city_code = '972', 
                        phone_number = '972-000-787', 
                        extension = '234', 
                        id = '3', 
                        city_code = 'DEN', 
                        role = 'Mobile', )
                    ], 
                email = [
                    openapi_client.models.email.Email(
                        value = 'exampledomain@example.com', 
                        id = 'exampledomain@example.com', 
                        email_type = 'Work', 
                        comment = '', 
                        preferred_format = 'text/html', 
                        share_marketing = 'Yes', 
                        share_sync = 'Yes', 
                        opt_out_ind = 'Yes', 
                        opt_in_status = 'OptedIn', 
                        opt_in_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        opt_out_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        valid_ind = True, 
                        provisioned_ind = True, )
                    ], 
                passenger_type_code = 'CHD', 
                nationality = 'AL', 
                customer_loyalty = [
                    openapi_client.models.customer_loyalty.CustomerLoyalty(
                        value = '132456', 
                        id = 'Loyalty_1', 
                        priority = 2, 
                        program_id = 'United', 
                        program_name = 'Mileage Plus', 
                        supplier_type = 'Airline', 
                        supplier = 'UA', 
                        tier = 'Silver', 
                        share_with_supplier = [
                            'LH NH SQ'
                            ], 
                        card_holder_name = 'John Smith', 
                        validated_ind = True, )
                    ], 
                alternate_contact = [
                    openapi_client.models.alternate_contact.AlternateContact(
                        @type = 'AlternateContact', 
                        id = '', 
                        contact_type = 'Relative', 
                        relation = 'Mother', 
                        person_name = openapi_client.models.person_name.PersonName(
                            @type = 'PersonNameDetail', 
                            prefix = 'Mr', 
                            given = 'John', 
                            middle = 'Erick', 
                            surname = 'Smith', ), 
                        address = [
                            openapi_client.models.address.Address(
                                @type = 'AddressDetail', 
                                id = 'Address_1', 
                                bldg_room = openapi_client.models.address_bldg_room.AddressBldgRoom(
                                    value = 'Moore House, Room 101, 23 ABC Street, Windsor, Berkshire, United Kingdom, SL6 51A', 
                                    bulding_ind = True, ), 
                                number = openapi_client.models.address_street_number.AddressStreetNumber(
                                    value = '23B ABC Street, Windsor, Berkshire, United Kingdom, SL6 51A', 
                                    street_nmbr_suffix = 'B', 
                                    street_direction = 'NW', 
                                    rural_route_nmbr = '76', 
                                    po_box = '1001', ), 
                                street = 'ABC Street', 
                                address_line = S Havana,Opposite to USPS, 
                                city = 'Windsor', 
                                county = 'Berkshire', 
                                state_prov = openapi_client.models.state_prov.StateProv(
                                    value = 'CA', 
                                    name = 'California', ), 
                                country = openapi_client.models.country.Country(
                                    value = 'USA', 
                                    id = '23', 
                                    name = 'United States', 
                                    code_context = 'IATA', ), 
                                postal_code = 'Sl6 1AB', 
                                addressee = '', 
                                role = 'Delivery', )
                            ], 
                        telephone = [
                            openapi_client.models.telephone.Telephone(
                                @type = 'Telephone', 
                                country_access_code = '1', 
                                area_city_code = '972', 
                                phone_number = '972-000-787', 
                                extension = '234', 
                                id = '3', 
                                city_code = 'DEN', )
                            ], 
                        email = [
                            openapi_client.models.email.Email(
                                value = 'exampledomain@example.com', 
                                id = 'exampledomain@example.com', 
                                email_type = 'Work', 
                                comment = '', 
                                preferred_format = 'text/html', 
                                share_marketing = 'Yes', 
                                share_sync = 'Yes', 
                                opt_out_ind = 'Yes', 
                                opt_in_status = 'OptedIn', 
                                opt_in_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                opt_out_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                valid_ind = True, 
                                provisioned_ind = True, )
                            ], 
                        emergency_ind = True, 
                        default_ind = True, )
                    ], 
                travel_document = [
                    openapi_client.models.travel_document.TravelDocument(
                        @type = 'TravelDocumentDetail', 
                        doc_number = 'B37201', 
                        doc_type = 'Passport', 
                        issue_date = 'Sun Oct 13 10:00:00 AEST 2002', 
                        expire_date = 'Wed Nov 13 11:00:00 AEDT 2002', 
                        state_prov_code = '44', 
                        place_of_issue = 'Birmingham', 
                        issue_country = 'CA', 
                        birth_date = 'Sat Apr 22 10:00:00 AEST 1995', 
                        birth_country = 'AR', 
                        birth_place = 'Ontario', 
                        residence = '1st section 8th st', 
                        id = '34', 
                        gender = 'Male', 
                        nationality = 'BR', 
                        person_name = openapi_client.models.person_name.PersonName(
                            @type = 'PersonNameDetail', 
                            prefix = 'Mr', 
                            given = 'John', 
                            middle = 'Erick', 
                            surname = 'Smith', ), )
                    ], 
                comments = openapi_client.models.comments.Comments(
                    @type = 'Comments', 
                    comment = ["check-in","boarded"], ), 
                rail_discount_card = [
                    openapi_client.models.rail_discount_card.RailDiscountCard(
                        value = '20 Perecnt', 
                        supplier_code = 'Enco', 
                        reference_number = '134256', )
                    ], 
                accompanied_by_infant_ind = True
            )
        else :
            return Traveler(
                person_name = openapi_client.models.person_name.PersonName(
                    @type = 'PersonNameDetail', 
                    prefix = 'Mr', 
                    given = 'John', 
                    middle = 'Erick', 
                    surname = 'Smith', ),
        )
        """

    def testTraveler(self):
        """Test Traveler"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
