# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.prohibited_vendors import ProhibitedVendors  # noqa: E501
from openapi_client.rest import ApiException

class TestProhibitedVendors(unittest.TestCase):
    """ProhibitedVendors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProhibitedVendors
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProhibitedVendors`
        """
        model = openapi_client.models.prohibited_vendors.ProhibitedVendors()  # noqa: E501
        if include_optional :
            return ProhibitedVendors(
                vendor = [
                    openapi_client.models.company_name.CompanyName(
                        value = '', 
                        id = '2', 
                        division = 'Travel Division', 
                        department = 'Adventure department', 
                        short_name = 'Aventure Inc', 
                        code = 'AI', 
                        code_context = 'internal', 
                        system_of_record = [
                            '["1G","1V","MB","HZ"]'
                            ], )
                    ]
            )
        else :
            return ProhibitedVendors(
                vendor = [
                    openapi_client.models.company_name.CompanyName(
                        value = '', 
                        id = '2', 
                        division = 'Travel Division', 
                        department = 'Adventure department', 
                        short_name = 'Aventure Inc', 
                        code = 'AI', 
                        code_context = 'internal', 
                        system_of_record = [
                            '["1G","1V","MB","HZ"]'
                            ], )
                    ],
        )
        """

    def testProhibitedVendors(self):
        """Test ProhibitedVendors"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
