# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.payment_card_type_enum import PaymentCardTypeEnum  # noqa: E501
from openapi_client.rest import ApiException

class TestPaymentCardTypeEnum(unittest.TestCase):
    """PaymentCardTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentCardTypeEnum(self):
        """Test PaymentCardTypeEnum"""
        # inst = PaymentCardTypeEnum()

if __name__ == '__main__':
    unittest.main()
