# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.search_air_api import SearchAirApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSearchAirApi(unittest.TestCase):
    """SearchAirApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.search_air_api.SearchAirApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_build_next_air_search(self):
        """Test case for build_next_air_search

        Search for flights on next leg  # noqa: E501
        """
        pass

    def test_build_options_air_search(self):
        """Test case for build_options_air_search

        Return all upsells on a specific flight  # noqa: E501
        """
        pass

    def test_create_air_search(self):
        """Test case for create_air_search

        Initial flight search  # noqa: E501
        """
        pass

    def test_get_page_air_search(self):
        """Test case for get_page_air_search

        Return additional search results (pagination)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
