# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.change import Change  # noqa: E501
from openapi_client.rest import ApiException

class TestChange(unittest.TestCase):
    """Change unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Change
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Change`
        """
        model = openapi_client.models.change.Change()  # noqa: E501
        if include_optional :
            return Change(
                type = 'ChangePermitted', 
                product_refs = ["baloon","food","accesories"], 
                segment_sequence = [34,56,678,2]
            )
        else :
            return Change(
                type = 'ChangePermitted',
        )
        """

    def testChange(self):
        """Test Change"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
