# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.cancellation_hold import CancellationHold  # noqa: E501
from openapi_client.rest import ApiException

class TestCancellationHold(unittest.TestCase):
    """CancellationHold unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CancellationHold
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CancellationHold`
        """
        model = openapi_client.models.cancellation_hold.CancellationHold()  # noqa: E501
        if include_optional :
            return CancellationHold(
                locator = openapi_client.models.locator.Locator(
                    value = 'ZXG25P', 
                    locator_type = 'Locator', 
                    source = '1G', 
                    source_context = 'Travelport', 
                    ota_type = '14.UIT', 
                    creation_date = 'Tue Mar 01 11:00:00 AEDT 2022', )
            )
        else :
            return CancellationHold(
        )
        """

    def testCancellationHold(self):
        """Test CancellationHold"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
