# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.reservation_query_search_criteria_reservation import ReservationQuerySearchCriteriaReservation  # noqa: E501
from openapi_client.rest import ApiException

class TestReservationQuerySearchCriteriaReservation(unittest.TestCase):
    """ReservationQuerySearchCriteriaReservation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReservationQuerySearchCriteriaReservation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReservationQuerySearchCriteriaReservation`
        """
        model = openapi_client.models.reservation_query_search_criteria_reservation.ReservationQuerySearchCriteriaReservation()  # noqa: E501
        if include_optional :
            return ReservationQuerySearchCriteriaReservation(
                type = 'ReservationQuerySearchCriteriaReservation', 
                person_name = openapi_client.models.person_name.PersonName(
                    @type = 'PersonNameDetail', 
                    prefix = 'Mr', 
                    given = 'John', 
                    middle = 'Erick', 
                    surname = 'Smith', ), 
                departure_date = 'Thu Mar 03 11:00:00 AEDT 2022', 
                departure_date_range = openapi_client.models.date_range.DateRange(
                    start = 'Fri Mar 03 11:00:00 AEDT 2023', 
                    end = 'Fri Mar 03 11:00:00 AEDT 2023', ), 
                departure = 'Atlanta, GA - ATL', 
                arrival = 'Atlanta, GA - ATL', 
                detail_view_ind = True
            )
        else :
            return ReservationQuerySearchCriteriaReservation(
                type = 'ReservationQuerySearchCriteriaReservation',
        )
        """

    def testReservationQuerySearchCriteriaReservation(self):
        """Test ReservationQuerySearchCriteriaReservation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
