# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.brand_api import BrandApi  # noqa: E501
from openapi_client.rest import ApiException


class TestBrandApi(unittest.TestCase):
    """BrandApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.brand_api.BrandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_brand(self):
        """Test case for create_brand

        Follow-on request for full brand pricing  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
