# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.flight_segment import FlightSegment  # noqa: E501
from openapi_client.rest import ApiException

class TestFlightSegment(unittest.TestCase):
    """FlightSegment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FlightSegment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlightSegment`
        """
        model = openapi_client.models.flight_segment.FlightSegment()  # noqa: E501
        if include_optional :
            return FlightSegment(
                type = 'FlightSegment', 
                id = '2304', 
                sequence = 65, 
                connection_duration = '60', 
                flight = openapi_client.models.flight_id.FlightID(
                    @type = 'FlightDetail', 
                    id = '126', 
                    flight_ref = 'pln0845', 
                    identifier = openapi_client.models.identifier.Identifier(
                        value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                        authority = 'TVPT', ), ), 
                operational_status = openapi_client.models.operational_status_enum.OperationalStatusENUM(
                    value = 'FlightBoarding', ), 
                bound_flights_ind = True, 
                co2_actual = openapi_client.models.measurement.Measurement(
                    value = 2.22, 
                    measurement_type = 'Width', 
                    unit = 'Miles', )
            )
        else :
            return FlightSegment(
                sequence = 65,
                flight = openapi_client.models.flight_id.FlightID(
                    @type = 'FlightDetail', 
                    id = '126', 
                    flight_ref = 'pln0845', 
                    identifier = openapi_client.models.identifier.Identifier(
                        value = 'A0656EFF-FAF4-456F-B061-0161008D7C4E', 
                        authority = 'TVPT', ), ),
        )
        """

    def testFlightSegment(self):
        """Test FlightSegment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
