# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.discount import Discount  # noqa: E501
from openapi_client.rest import ApiException

class TestDiscount(unittest.TestCase):
    """Discount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Discount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Discount`
        """
        model = openapi_client.models.discount.Discount()  # noqa: E501
        if include_optional :
            return Discount(
                value = 20.22, 
                description = 'Spring discount on group bookings', 
                currency_code = 'USD', 
                code_authority = 'ISO', 
                decimal_place = 2, 
                decimal_authority = 'ISO'
            )
        else :
            return Discount(
                currency_code = 'USD',
                code_authority = 'ISO',
                decimal_place = 2,
        )
        """

    def testDiscount(self):
        """Test Discount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
