# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import Field, conlist
from openapi_client.models.ancillary_air import AncillaryAir
from openapi_client.models.ancillary_description import AncillaryDescription
from openapi_client.models.baggage_type_enum import BaggageTypeEnum
from openapi_client.models.measurement import Measurement

class AncillaryAirBaggage(AncillaryAir):
    """
    AncillaryAirBaggage
    """
    baggage_type: BaggageTypeEnum = Field(..., alias="BaggageType")
    measurement: conlist(Measurement, max_items=6, min_items=1) = Field(..., alias="Measurement")
    __properties = ["@type", "quantity", "Description", "FlightRef", "BaggageType", "Measurement"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AncillaryAirBaggage:
        """Create an instance of AncillaryAirBaggage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in description (list)
        _items = []
        if self.description:
            for _item in self.description:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Description'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in measurement (list)
        _items = []
        if self.measurement:
            for _item in self.measurement:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Measurement'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AncillaryAirBaggage:
        """Create an instance of AncillaryAirBaggage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AncillaryAirBaggage.parse_obj(obj)

        _obj = AncillaryAirBaggage.parse_obj({
            "type": obj.get("@type"),
            "quantity": obj.get("quantity"),
            "description": [AncillaryDescription.from_dict(_item) for _item in obj.get("Description")] if obj.get("Description") is not None else None,
            "flight_ref": obj.get("FlightRef"),
            "baggage_type": obj.get("BaggageType"),
            "measurement": [Measurement.from_dict(_item) for _item in obj.get("Measurement")] if obj.get("Measurement") is not None else None
        })
        return _obj


