# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AvailabilitySourceCodeENUM(str, Enum):
    """
    A code representing the source of the flight availability
    """

    """
    allowed enum values
    """
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    F = 'F'
    G = 'G'
    H = 'H'
    I = 'I'
    J = 'J'
    K = 'K'
    L = 'L'
    M = 'M'
    N = 'N'
    O = 'O'
    P = 'P'
    Q = 'Q'
    S = 'S'
    T = 'T'
    U = 'U'
    X = 'X'
    Y = 'Y'
    Z = 'Z'

    @classmethod
    def from_json(cls, json_str: str) -> AvailabilitySourceCodeENUM:
        """Create an instance of AvailabilitySourceCodeENUM from a JSON string"""
        return AvailabilitySourceCodeENUM(json.loads(json_str))


