# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, constr

class BedConfiguration(BaseModel):
    """
    BedConfiguration
    """
    quantity: Optional[StrictInt] = Field(None, description="The number of bed of this type and size in the room")
    bed_type: Optional[constr(strict=True, max_length=32)] = Field(None, alias="bedType", description="Configuration of bed(s) in room.")
    size: Optional[constr(strict=True, max_length=32)] = Field(None, description="Size of bed(s) in the room.")
    __properties = ["quantity", "bedType", "size"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BedConfiguration:
        """Create an instance of BedConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BedConfiguration:
        """Create an instance of BedConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BedConfiguration.parse_obj(obj)

        _obj = BedConfiguration.parse_obj({
            "quantity": obj.get("quantity"),
            "bed_type": obj.get("bedType"),
            "size": obj.get("size")
        })
        return _obj


