# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class BrandTargetEnum(str, Enum):
    """
    The audience targeted for the brand information
    """

    """
    allowed enum values
    """
    STRAPLINE = 'Strapline'
    MARKETINGAGENT = 'MarketingAgent'
    MARKETINGCONSUMER = 'MarketingConsumer'
    EXTERNAL = 'External'
    SHORT = 'Short'
    AGENT = 'Agent'
    CONSUMER = 'Consumer'
    UPSELL = 'Upsell'

    @classmethod
    def from_json(cls, json_str: str) -> BrandTargetEnum:
        """Create an instance of BrandTargetEnum from a JSON string"""
        return BrandTargetEnum(json.loads(json_str))


