# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist, constr
from openapi_client.models.offer_identifier import OfferIdentifier
from openapi_client.models.product_identifier import ProductIdentifier

class BuildFromOfferList(BaseModel):
    """
    BuildFromOfferList
    """
    type: Optional[StrictStr] = Field(None, alias="@type")
    offer_list_identifier: constr(strict=True, max_length=128) = Field(..., alias="OfferListIdentifier", description="The OfferListIdentifer (GUID) to retrieve the OfferList from cache")
    offer_identifier: conlist(OfferIdentifier, max_items=1000, min_items=1) = Field(..., alias="OfferIdentifier")
    product_identifier: Optional[conlist(ProductIdentifier, max_items=10)] = Field(None, alias="ProductIdentifier")
    segment_sequence: Optional[StrictInt] = Field(None, alias="SegmentSequence", description="The segmentSequence within the product the action is being requested for. Used when multiple exist within a product")
    __properties = ["@type", "OfferListIdentifier", "OfferIdentifier", "ProductIdentifier", "SegmentSequence"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BuildFromOfferList:
        """Create an instance of BuildFromOfferList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in offer_identifier (list)
        _items = []
        if self.offer_identifier:
            for _item in self.offer_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['OfferIdentifier'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in product_identifier (list)
        _items = []
        if self.product_identifier:
            for _item in self.product_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ProductIdentifier'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BuildFromOfferList:
        """Create an instance of BuildFromOfferList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BuildFromOfferList.parse_obj(obj)

        _obj = BuildFromOfferList.parse_obj({
            "type": obj.get("@type"),
            "offer_list_identifier": obj.get("OfferListIdentifier"),
            "offer_identifier": [OfferIdentifier.from_dict(_item) for _item in obj.get("OfferIdentifier")] if obj.get("OfferIdentifier") is not None else None,
            "product_identifier": [ProductIdentifier.from_dict(_item) for _item in obj.get("ProductIdentifier")] if obj.get("ProductIdentifier") is not None else None,
            "segment_sequence": obj.get("SegmentSequence")
        })
        return _obj


