# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictStr, conint, conlist
from openapi_client.models.fare_rule_category_enum import FareRuleCategoryEnum
from openapi_client.models.fare_rule_enum import FareRuleEnum
from openapi_client.models.payment_criteria import PaymentCriteria

class BuildOptions(BaseModel):
    """
    BuildOptions
    """
    type: StrictStr = Field(..., alias="@type")
    max_number_of_upsells_to_return: Optional[conint(strict=True, ge=0)] = Field(None, alias="maxNumberOfUpsellsToReturn", description="NonnegativeInteger")
    payment_criteria: Optional[PaymentCriteria] = Field(None, alias="PaymentCriteria")
    fare_rule_type: Optional[FareRuleEnum] = Field(None, alias="FareRuleType")
    fare_rule_category: Optional[conlist(FareRuleCategoryEnum, max_items=10)] = Field(None, alias="FareRuleCategory")
    return_branded_fares_ind: Optional[StrictBool] = Field(None, alias="returnBrandedFaresInd")
    __properties = ["@type", "maxNumberOfUpsellsToReturn", "PaymentCriteria", "FareRuleType", "FareRuleCategory", "returnBrandedFaresInd"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    # JSON field name that stores the object type
    __discriminator_property_name = '@type'

    # discriminator mappings
    __discriminator_value_class_map = {
        'BuildOptionsFromCatalogProductOptions': 'BuildOptionsFromCatalogProductOptions',
        'BuildOptionsFromProducts': 'BuildOptionsFromProducts'
    }

    @classmethod
    def get_discriminator_value(cls, obj: dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union(BuildOptionsFromCatalogProductOptions, BuildOptionsFromProducts):
        """Create an instance of BuildOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of payment_criteria
        if self.payment_criteria:
            _dict['PaymentCriteria'] = self.payment_criteria.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Union(BuildOptionsFromCatalogProductOptions, BuildOptionsFromProducts):
        """Create an instance of BuildOptions from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type:
            klass = globals()[object_type]
            return klass.from_dict(obj)
        else:
            raise ValueError("BuildOptions failed to lookup discriminator value from " +
                             json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                             ", mapping: " + json.dumps(cls.__discriminator_value_class_map))

from openapi_client.models.build_options_from_catalog_product_options import BuildOptionsFromCatalogProductOptions
from openapi_client.models.build_options_from_products import BuildOptionsFromProducts
BuildOptions.update_forward_refs()

