# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import Field
from openapi_client.models.build_from_products_request import BuildFromProductsRequest
from openapi_client.models.build_options import BuildOptions
from openapi_client.models.fare_rule_category_enum import FareRuleCategoryEnum
from openapi_client.models.fare_rule_enum import FareRuleEnum
from openapi_client.models.payment_criteria import PaymentCriteria

class BuildOptionsFromProducts(BuildOptions):
    """
    BuildOptionsFromProducts
    """
    build_from_products_request: BuildFromProductsRequest = Field(..., alias="BuildFromProductsRequest")
    __properties = ["@type", "maxNumberOfUpsellsToReturn", "PaymentCriteria", "FareRuleType", "FareRuleCategory", "returnBrandedFaresInd", "BuildFromProductsRequest"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BuildOptionsFromProducts:
        """Create an instance of BuildOptionsFromProducts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of payment_criteria
        if self.payment_criteria:
            _dict['PaymentCriteria'] = self.payment_criteria.to_dict()
        # override the default output from pydantic by calling `to_dict()` of build_from_products_request
        if self.build_from_products_request:
            _dict['BuildFromProductsRequest'] = self.build_from_products_request.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BuildOptionsFromProducts:
        """Create an instance of BuildOptionsFromProducts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BuildOptionsFromProducts.parse_obj(obj)

        _obj = BuildOptionsFromProducts.parse_obj({
            "type": obj.get("@type"),
            "max_number_of_upsells_to_return": obj.get("maxNumberOfUpsellsToReturn"),
            "payment_criteria": PaymentCriteria.from_dict(obj.get("PaymentCriteria")) if obj.get("PaymentCriteria") is not None else None,
            "fare_rule_type": obj.get("FareRuleType"),
            "fare_rule_category": obj.get("FareRuleCategory"),
            "return_branded_fares_ind": obj.get("returnBrandedFaresInd"),
            "build_from_products_request": BuildFromProductsRequest.from_dict(obj.get("BuildFromProductsRequest")) if obj.get("BuildFromProductsRequest") is not None else None
        })
        return _obj


