# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictStr, conlist
from openapi_client.models.ancillary_offering_identifier import AncillaryOfferingIdentifier
from openapi_client.models.catalog_offering_identifier import CatalogOfferingIdentifier
from openapi_client.models.catalog_offerings_identifier import CatalogOfferingsIdentifier
from openapi_client.models.product_identifier import ProductIdentifier

class BuildFromCatalogOfferingsRequest(BaseModel):
    """
    BuildFromCatalogOfferingsRequest
    """
    type: StrictStr = Field(..., alias="@type")
    catalog_offerings_identifier: CatalogOfferingsIdentifier = Field(..., alias="CatalogOfferingsIdentifier")
    catalog_offering_identifier: CatalogOfferingIdentifier = Field(..., alias="CatalogOfferingIdentifier")
    product_identifier: conlist(ProductIdentifier, max_items=10, min_items=1) = Field(..., alias="ProductIdentifier")
    ancillary_offering_identifier: Optional[conlist(AncillaryOfferingIdentifier, max_items=100)] = Field(None, alias="AncillaryOfferingIdentifier")
    __properties = ["@type", "CatalogOfferingsIdentifier", "CatalogOfferingIdentifier", "ProductIdentifier", "AncillaryOfferingIdentifier"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    # JSON field name that stores the object type
    __discriminator_property_name = '@type'

    # discriminator mappings
    __discriminator_value_class_map = {
        'BuildFromCatalogOfferingsRequestAir': 'BuildFromCatalogOfferingsRequestAir'
    }

    @classmethod
    def get_discriminator_value(cls, obj: dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union(BuildFromCatalogOfferingsRequestAir):
        """Create an instance of BuildFromCatalogOfferingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of catalog_offerings_identifier
        if self.catalog_offerings_identifier:
            _dict['CatalogOfferingsIdentifier'] = self.catalog_offerings_identifier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of catalog_offering_identifier
        if self.catalog_offering_identifier:
            _dict['CatalogOfferingIdentifier'] = self.catalog_offering_identifier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in product_identifier (list)
        _items = []
        if self.product_identifier:
            for _item in self.product_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ProductIdentifier'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ancillary_offering_identifier (list)
        _items = []
        if self.ancillary_offering_identifier:
            for _item in self.ancillary_offering_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AncillaryOfferingIdentifier'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Union(BuildFromCatalogOfferingsRequestAir):
        """Create an instance of BuildFromCatalogOfferingsRequest from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type:
            klass = globals()[object_type]
            return klass.from_dict(obj)
        else:
            raise ValueError("BuildFromCatalogOfferingsRequest failed to lookup discriminator value from " +
                             json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                             ", mapping: " + json.dumps(cls.__discriminator_value_class_map))

from openapi_client.models.build_from_catalog_offerings_request_air import BuildFromCatalogOfferingsRequestAir
BuildFromCatalogOfferingsRequest.update_forward_refs()

