# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CabinAirEnum(str, Enum):
    """
    Specifies the cabin type (e.g. first, business, economy).
    """

    """
    allowed enum values
    """
    PREMIUMFIRST = 'PremiumFirst'
    FIRST = 'First'
    BUSINESS = 'Business'
    PREMIUMECONOMY = 'PremiumEconomy'
    ECONOMY = 'Economy'

    @classmethod
    def from_json(cls, json_str: str) -> CabinAirEnum:
        """Create an instance of CabinAirEnum from a JSON string"""
        return CabinAirEnum(json.loads(json_str))


