# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ConfirmationStatusEnum(str, Enum):
    """
    Status returned in a response for a two or more phase commitment process
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    CONFIRMED = 'Confirmed'
    CANCELLED = 'Cancelled'
    REJECTED = 'Rejected'

    @classmethod
    def from_json(cls, json_str: str) -> ConfirmationStatusEnum:
        """Create an instance of ConfirmationStatusEnum from a JSON string"""
        return ConfirmationStatusEnum(json.loads(json_str))


