# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr, validator
from openapi_client.models.opt_in_status_enum import OptInStatusEnum
from openapi_client.models.yes_no_inherit_enum import YesNoInheritEnum

class Email(BaseModel):
    """
    Electronic email addresses, in IETF specified format.
    """
    value: Optional[constr(strict=True, max_length=128)] = None
    id: Optional[StrictStr] = Field(None, description="Electronic email addresses, in IETF specified format.")
    email_type: Optional[constr(strict=True)] = Field(None, alias="emailType", description="Type of the e-mail")
    comment: Optional[constr(strict=True, max_length=4096)] = Field(None, description="Assigned Type: c-1100:StringText")
    preferred_format: Optional[constr(strict=True, max_length=32)] = Field(None, alias="preferredFormat", description="Mime media type")
    share_marketing: Optional[YesNoInheritEnum] = Field(None, alias="shareMarketing")
    share_sync: Optional[YesNoInheritEnum] = Field(None, alias="shareSync")
    opt_out_ind: Optional[YesNoInheritEnum] = Field(None, alias="optOutInd")
    opt_in_status: Optional[OptInStatusEnum] = Field(None, alias="optInStatus")
    opt_in_date: Optional[datetime] = Field(None, alias="optInDate", description="The datetime of receiving the opt in notice")
    opt_out_date: Optional[datetime] = Field(None, alias="optOutDate", description="The datetime the opt out notice was received")
    valid_ind: Optional[StrictBool] = Field(None, alias="validInd", description="If true, this is a valid email address that has been system verified via a successful email transmission.")
    provisioned_ind: Optional[StrictBool] = Field(None, alias="provisionedInd", description="If true then the email address came from the provisioning process")
    __properties = ["value", "id", "emailType", "comment", "preferredFormat", "shareMarketing", "shareSync", "optOutInd", "optInStatus", "optInDate", "optOutDate", "validInd", "provisionedInd"]

    @validator('email_type')
    def email_type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"[0-9A-Z]{1,3}(\.[A-Z]{3}(\.X){0,1}){0,1}", value):
            raise ValueError(r"must validate the regular expression /[0-9A-Z]{1,3}(\.[A-Z]{3}(\.X){0,1}){0,1}/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Email:
        """Create an instance of Email from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Email:
        """Create an instance of Email from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Email.parse_obj(obj)

        _obj = Email.parse_obj({
            "value": obj.get("value"),
            "id": obj.get("id"),
            "email_type": obj.get("emailType"),
            "comment": obj.get("comment"),
            "preferred_format": obj.get("preferredFormat"),
            "share_marketing": obj.get("shareMarketing"),
            "share_sync": obj.get("shareSync"),
            "opt_out_ind": obj.get("optOutInd"),
            "opt_in_status": obj.get("optInStatus"),
            "opt_in_date": obj.get("optInDate"),
            "opt_out_date": obj.get("optOutDate"),
            "valid_ind": obj.get("validInd"),
            "provisioned_ind": obj.get("provisionedInd")
        })
        return _obj


