# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ListPaymentCardIssuerEnumBase(str, Enum):
    """
    Source: OpenTravel
    """

    """
    allowed enum values
    """
    VISA = 'VISA'
    USAIRWAYS = 'USAirways'
    UNITEDAIRLINES = 'UnitedAirlines'
    STARWOODHOTELS = 'StarwoodHotels'
    SOUTHWESTAIRLINES = 'SouthwestAirlines'
    RITZCARLTON = 'RitzCarlton'
    MASTERCARD = 'Mastercard'
    MARIOTT = 'Mariott'
    HYATT = 'Hyatt'
    HILTON = 'Hilton'
    EUROCARD = 'Eurocard'
    DISNEY = 'Disney'
    DISCOVERCARD = 'DiscoverCard'
    DELTAAIRLINES = 'DeltaAirlines'
    CONTINENTALAIRLINES = 'ContinentalAirlines'
    CITIBANK = 'Citibank'
    CHASE = 'Chase'
    CAPITALONE = 'CapitalOne'
    BRITISHAIRWAYS = 'BritishAirways'
    BANKOFAMERICA = 'BankOfAmerica'
    AMERICANEXPRESS = 'AmericanExpress'

    @classmethod
    def from_json(cls, json_str: str) -> ListPaymentCardIssuerEnumBase:
        """Create an instance of ListPaymentCardIssuerEnumBase from a JSON string"""
        return ListPaymentCardIssuerEnumBase(json.loads(json_str))


