# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openapi_client.models.payment_criteria import PaymentCriteria
from openapi_client.models.pricing_modifiers_air import PricingModifiersAir
from openapi_client.models.product_id import ProductID

class OfferQueryBuildFromShoppingCartProducts(BaseModel):
    """
    OfferQueryBuildFromShoppingCartProducts
    """
    type: StrictStr = Field(..., alias="@type")
    pricing_modifiers_air: Optional[PricingModifiersAir] = Field(None, alias="PricingModifiersAir")
    product_identifier: Optional[conlist(ProductID, max_items=100)] = Field(None, alias="ProductIdentifier")
    payment_criteria: Optional[PaymentCriteria] = Field(None, alias="PaymentCriteria")
    __properties = ["@type", "PricingModifiersAir", "ProductIdentifier", "PaymentCriteria"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OfferQueryBuildFromShoppingCartProducts:
        """Create an instance of OfferQueryBuildFromShoppingCartProducts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of pricing_modifiers_air
        if self.pricing_modifiers_air:
            _dict['PricingModifiersAir'] = self.pricing_modifiers_air.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in product_identifier (list)
        _items = []
        if self.product_identifier:
            for _item in self.product_identifier:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ProductIdentifier'] = _items
        # override the default output from pydantic by calling `to_dict()` of payment_criteria
        if self.payment_criteria:
            _dict['PaymentCriteria'] = self.payment_criteria.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OfferQueryBuildFromShoppingCartProducts:
        """Create an instance of OfferQueryBuildFromShoppingCartProducts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OfferQueryBuildFromShoppingCartProducts.parse_obj(obj)

        _obj = OfferQueryBuildFromShoppingCartProducts.parse_obj({
            "type": obj.get("@type"),
            "pricing_modifiers_air": PricingModifiersAir.from_dict(obj.get("PricingModifiersAir")) if obj.get("PricingModifiersAir") is not None else None,
            "product_identifier": [ProductID.from_dict(_item) for _item in obj.get("ProductIdentifier")] if obj.get("ProductIdentifier") is not None else None,
            "payment_criteria": PaymentCriteria.from_dict(obj.get("PaymentCriteria")) if obj.get("PaymentCriteria") is not None else None
        })
        return _obj


