# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conint, conlist, constr, validator
from openapi_client.models.customer_loyalty import CustomerLoyalty
from openapi_client.models.traveler_geographic_location import TravelerGeographicLocation

class PassengerCriteria(BaseModel):
    """
    PassengerCriteria
    """
    type: Optional[StrictStr] = Field(None, alias="@type")
    number: Optional[conint(strict=True, ge=0)] = Field(None, description="Number")
    age: Optional[StrictInt] = Field(None, description="Age")
    passenger_type_code: Optional[constr(strict=True, max_length=5, min_length=3)] = Field(None, alias="passengerTypeCode", description="Passenger Type Code")
    customer_loyalty: Optional[conlist(CustomerLoyalty, max_items=100)] = Field(None, alias="CustomerLoyalty")
    traveler_geographic_location: Optional[TravelerGeographicLocation] = Field(None, alias="TravelerGeographicLocation")
    specified_passenger_type_code_only_ind: Optional[StrictBool] = Field(None, alias="specifiedPassengerTypeCodeOnlyInd", description="If true then the Offering/Offer will only be returned for the specific passengerTypeCode")
    __properties = ["@type", "number", "age", "passengerTypeCode", "CustomerLoyalty", "TravelerGeographicLocation", "specifiedPassengerTypeCodeOnlyInd"]

    @validator('passenger_type_code')
    def passenger_type_code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"([a-zA-Z0-9]{3,5})", value):
            raise ValueError(r"must validate the regular expression /([a-zA-Z0-9]{3,5})/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PassengerCriteria:
        """Create an instance of PassengerCriteria from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in customer_loyalty (list)
        _items = []
        if self.customer_loyalty:
            for _item in self.customer_loyalty:
                if _item:
                    _items.append(_item.to_dict())
            _dict['CustomerLoyalty'] = _items
        # override the default output from pydantic by calling `to_dict()` of traveler_geographic_location
        if self.traveler_geographic_location:
            _dict['TravelerGeographicLocation'] = self.traveler_geographic_location.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PassengerCriteria:
        """Create an instance of PassengerCriteria from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PassengerCriteria.parse_obj(obj)

        _obj = PassengerCriteria.parse_obj({
            "type": obj.get("@type"),
            "number": obj.get("number"),
            "age": obj.get("age"),
            "passenger_type_code": obj.get("passengerTypeCode"),
            "customer_loyalty": [CustomerLoyalty.from_dict(_item) for _item in obj.get("CustomerLoyalty")] if obj.get("CustomerLoyalty") is not None else None,
            "traveler_geographic_location": TravelerGeographicLocation.from_dict(obj.get("TravelerGeographicLocation")) if obj.get("TravelerGeographicLocation") is not None else None,
            "specified_passenger_type_code_only_ind": obj.get("specifiedPassengerTypeCodeOnlyInd")
        })
        return _obj


