# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PictureofEnum(str, Enum):
    """
    PictureofEnum
    """

    """
    allowed enum values
    """
    EXTERIOR = 'Exterior'
    LOBBY = 'Lobby'
    POOL = 'Pool'
    RESTAURANT = 'Restaurant'
    HEALTHCLUB = 'HealthClub'
    GUESTROOM = 'GuestRoom'
    SUITE = 'Suite'
    CONFERENCEROOM = 'ConferenceRoom'
    BALLROOM = 'Ballroom'
    GOLF = 'Golf'
    BEACH = 'Beach'
    SPA = 'Spa'
    BAR = 'Bar'
    RECREATIONAL = 'Recreational'
    ROOMAMENITY = 'RoomAmenity'
    POPERTYAMENITY = 'PopertyAmenity'
    BUSINESSCENTRE = 'BusinessCentre'

    @classmethod
    def from_json(cls, json_str: str) -> PictureofEnum:
        """Create an instance of PictureofEnum from a JSON string"""
        return PictureofEnum(json.loads(json_str))


