# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr
from openapi_client.models.sub_policy import SubPolicy
from openapi_client.models.text_formatted import TextFormatted

class Policy(BaseModel):
    """
    Policy
    """
    type: StrictStr = Field(..., alias="@type")
    title: Optional[constr(strict=True, max_length=512)] = Field(None, description="Assigned Type: c-1100:String")
    text_formatted: Optional[conlist(TextFormatted, max_items=50)] = Field(None, alias="TextFormatted")
    sub_policy: Optional[conlist(SubPolicy, max_items=10)] = Field(None, alias="SubPolicy")
    __properties = ["@type", "title", "TextFormatted", "SubPolicy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Policy:
        """Create an instance of Policy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in text_formatted (list)
        _items = []
        if self.text_formatted:
            for _item in self.text_formatted:
                if _item:
                    _items.append(_item.to_dict())
            _dict['TextFormatted'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_policy (list)
        _items = []
        if self.sub_policy:
            for _item in self.sub_policy:
                if _item:
                    _items.append(_item.to_dict())
            _dict['SubPolicy'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Policy:
        """Create an instance of Policy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Policy.parse_obj(obj)

        _obj = Policy.parse_obj({
            "type": obj.get("@type"),
            "title": obj.get("title"),
            "text_formatted": [TextFormatted.from_dict(_item) for _item in obj.get("TextFormatted")] if obj.get("TextFormatted") is not None else None,
            "sub_policy": [SubPolicy.from_dict(_item) for _item in obj.get("SubPolicy")] if obj.get("SubPolicy") is not None else None
        })
        return _obj


