# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr, validator
from openapi_client.models.document_type_enum import DocumentTypeEnum

class PreviousIssue(BaseModel):
    """
    PreviousIssue
    """
    value: Optional[constr(strict=True, max_length=32)] = None
    issuing_city: Optional[constr(strict=True, max_length=3, min_length=3)] = Field(None, alias="issuingCity")
    issue_date: Optional[constr(strict=True)] = Field(None, alias="issueDate")
    agency_code_iata: Optional[constr(strict=True)] = Field(None, alias="agencyCodeIATA")
    document_type: Optional[DocumentTypeEnum] = Field(None, alias="documentType")
    __properties = ["value", "issuingCity", "issueDate", "agencyCodeIATA", "documentType"]

    @validator('issuing_city')
    def issuing_city_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"([a-zA-Z]{3})", value):
            raise ValueError(r"must validate the regular expression /([a-zA-Z]{3})/")
        return value

    @validator('issue_date')
    def issue_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(\d{4}-\d{2}-\d{2})", value):
            raise ValueError(r"must validate the regular expression /(\d{4}-\d{2}-\d{2})/")
        return value

    @validator('agency_code_iata')
    def agency_code_iata_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"([0-9]{8})", value):
            raise ValueError(r"must validate the regular expression /([0-9]{8})/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PreviousIssue:
        """Create an instance of PreviousIssue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PreviousIssue:
        """Create an instance of PreviousIssue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PreviousIssue.parse_obj(obj)

        _obj = PreviousIssue.parse_obj({
            "value": obj.get("value"),
            "issuing_city": obj.get("issuingCity"),
            "issue_date": obj.get("issueDate"),
            "agency_code_iata": obj.get("agencyCodeIATA"),
            "document_type": obj.get("documentType")
        })
        return _obj


