# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import Field, StrictStr, conlist
from openapi_client.models.flight_segment import FlightSegment
from openapi_client.models.identifier import Identifier
from openapi_client.models.passenger_flight import PassengerFlight
from openapi_client.models.product import Product

class ProductAir(Product):
    """
    ProductAir
    """
    total_duration: Optional[StrictStr] = Field(None, alias="totalDuration", description="Total duration of all Segments that are part of this ProductAir")
    flight_segment: conlist(FlightSegment, max_items=99, min_items=1) = Field(..., alias="FlightSegment")
    passenger_flight: conlist(PassengerFlight, max_items=10, min_items=1) = Field(..., alias="PassengerFlight")
    __properties = ["@type", "id", "productRef", "Identifier", "Quantity", "totalDuration", "FlightSegment", "PassengerFlight"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProductAir:
        """Create an instance of ProductAir from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of identifier
        if self.identifier:
            _dict['Identifier'] = self.identifier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in flight_segment (list)
        _items = []
        if self.flight_segment:
            for _item in self.flight_segment:
                if _item:
                    _items.append(_item.to_dict())
            _dict['FlightSegment'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in passenger_flight (list)
        _items = []
        if self.passenger_flight:
            for _item in self.passenger_flight:
                if _item:
                    _items.append(_item.to_dict())
            _dict['PassengerFlight'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProductAir:
        """Create an instance of ProductAir from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProductAir.parse_obj(obj)

        _obj = ProductAir.parse_obj({
            "type": obj.get("@type"),
            "id": obj.get("id"),
            "product_ref": obj.get("productRef"),
            "identifier": Identifier.from_dict(obj.get("Identifier")) if obj.get("Identifier") is not None else None,
            "quantity": obj.get("Quantity"),
            "total_duration": obj.get("totalDuration"),
            "flight_segment": [FlightSegment.from_dict(_item) for _item in obj.get("FlightSegment")] if obj.get("FlightSegment") is not None else None,
            "passenger_flight": [PassengerFlight.from_dict(_item) for _item in obj.get("PassengerFlight")] if obj.get("PassengerFlight") is not None else None
        })
        return _obj


