# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist, constr

class Restriction(BaseModel):
    """
    Restriction
    """
    value: Optional[constr(strict=True, max_length=128)] = None
    segment_sequence_list: Optional[conlist(StrictInt)] = Field(None, alias="segmentSequenceList", description="Segment sequence list")
    product_ref: Optional[conlist(StrictStr)] = Field(None, alias="productRef", description="The productRef which the restriction applies to")
    __properties = ["value", "segmentSequenceList", "productRef"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Restriction:
        """Create an instance of Restriction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Restriction:
        """Create an instance of Restriction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Restriction.parse_obj(obj)

        _obj = Restriction.parse_obj({
            "value": obj.get("value"),
            "segment_sequence_list": obj.get("segmentSequenceList"),
            "product_ref": obj.get("productRef")
        })
        return _obj


