# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SearchRepresentationENUM(str, Enum):
    """
    Customize search result set as leg or journey based
    """

    """
    allowed enum values
    """
    LEG = 'Leg'
    JOURNEY = 'Journey'

    @classmethod
    def from_json(cls, json_str: str) -> SearchRepresentationENUM:
        """Create an instance of SearchRepresentationENUM from a JSON string"""
        return SearchRepresentationENUM(json.loads(json_str))


