# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapi_client.models.currency_amount import CurrencyAmount

class StopoverCharge(BaseModel):
    """
    StopoverCharge
    """
    type: Optional[StrictStr] = Field(None, alias="@type")
    id: StrictStr = Field(..., description="The ID of the stopoverCharge")
    quantity: StrictInt = Field(..., description="The quantity of stopovers permitted at this charge")
    amount: CurrencyAmount = Field(..., alias="Amount")
    alternative_amount: Optional[CurrencyAmount] = Field(None, alias="AlternativeAmount")
    __properties = ["@type", "id", "quantity", "Amount", "AlternativeAmount"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StopoverCharge:
        """Create an instance of StopoverCharge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['Amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of alternative_amount
        if self.alternative_amount:
            _dict['AlternativeAmount'] = self.alternative_amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StopoverCharge:
        """Create an instance of StopoverCharge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StopoverCharge.parse_obj(obj)

        _obj = StopoverCharge.parse_obj({
            "type": obj.get("@type"),
            "id": obj.get("id"),
            "quantity": obj.get("quantity"),
            "amount": CurrencyAmount.from_dict(obj.get("Amount")) if obj.get("Amount") is not None else None,
            "alternative_amount": CurrencyAmount.from_dict(obj.get("AlternativeAmount")) if obj.get("AlternativeAmount") is not None else None
        })
        return _obj


