# coding: utf-8

"""
    Akaris Travels Air

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 11.10.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr

class TravelerUpdatableItem(BaseModel):
    """
    TravelerUpdatableItem
    """
    type: StrictStr = Field(..., alias="@type")
    identifier: Optional[constr(strict=True, max_length=128)] = Field(None, alias="Identifier", description="A unique GUID to identify the TravelerUpdatableItem")
    addable_ind: Optional[StrictBool] = Field(None, alias="addableInd", description="If true the TravelerUpdateableItem can be added to the Traveler")
    modifiable_ind: Optional[StrictBool] = Field(None, alias="modifiableInd", description="If true the TravelerUpdateableItem can be modified in the Traveler")
    deletable_ind: Optional[StrictBool] = Field(None, alias="deletableInd", description="If true the TravelerUpdateableItem can be deleted from the Traveler")
    __properties = ["@type", "Identifier", "addableInd", "modifiableInd", "deletableInd"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    # JSON field name that stores the object type
    __discriminator_property_name = '@type'

    # discriminator mappings
    __discriminator_value_class_map = {
        'TravelerUpdatableItemAddress': 'TravelerUpdatableItemAddress',
        'TravelerUpdatableItemBirthDate': 'TravelerUpdatableItemBirthDate',
        'TravelerUpdatableItemCustomerLoyalty': 'TravelerUpdatableItemCustomerLoyalty',
        'TravelerUpdatableItemEmail': 'TravelerUpdatableItemEmail',
        'TravelerUpdatableItemGender': 'TravelerUpdatableItemGender',
        'TravelerUpdatableItemPersonName': 'TravelerUpdatableItemPersonName',
        'TravelerUpdatableItemTelephone': 'TravelerUpdatableItemTelephone',
        'TravelerUpdatableItemTravelDocument': 'TravelerUpdatableItemTravelDocument'
    }

    @classmethod
    def get_discriminator_value(cls, obj: dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union(TravelerUpdatableItemAddress, TravelerUpdatableItemBirthDate, TravelerUpdatableItemCustomerLoyalty, TravelerUpdatableItemEmail, TravelerUpdatableItemGender, TravelerUpdatableItemPersonName, TravelerUpdatableItemTelephone, TravelerUpdatableItemTravelDocument):
        """Create an instance of TravelerUpdatableItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Union(TravelerUpdatableItemAddress, TravelerUpdatableItemBirthDate, TravelerUpdatableItemCustomerLoyalty, TravelerUpdatableItemEmail, TravelerUpdatableItemGender, TravelerUpdatableItemPersonName, TravelerUpdatableItemTelephone, TravelerUpdatableItemTravelDocument):
        """Create an instance of TravelerUpdatableItem from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type:
            klass = globals()[object_type]
            return klass.from_dict(obj)
        else:
            raise ValueError("TravelerUpdatableItem failed to lookup discriminator value from " +
                             json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                             ", mapping: " + json.dumps(cls.__discriminator_value_class_map))

from openapi_client.models.traveler_updatable_item_address import TravelerUpdatableItemAddress
from openapi_client.models.traveler_updatable_item_birth_date import TravelerUpdatableItemBirthDate
from openapi_client.models.traveler_updatable_item_customer_loyalty import TravelerUpdatableItemCustomerLoyalty
from openapi_client.models.traveler_updatable_item_email import TravelerUpdatableItemEmail
from openapi_client.models.traveler_updatable_item_gender import TravelerUpdatableItemGender
from openapi_client.models.traveler_updatable_item_person_name import TravelerUpdatableItemPersonName
from openapi_client.models.traveler_updatable_item_telephone import TravelerUpdatableItemTelephone
from openapi_client.models.traveler_updatable_item_travel_document import TravelerUpdatableItemTravelDocument
TravelerUpdatableItem.update_forward_refs()

